# To use this file for CI delete "_android" in the name

.only-mr: &only-mr
  only:
    - merge_requests

.only-branch: &only-branch-tag
  only:
    - develop
    - master
    - tag

.only-tag-branch: &only-mr-branch-tag
  only:
    - merge_requests
    - develop
    - master
    - tag

variables:
  GROUPE_TESTEUR: "qa-team"

stages:
  - test
  - build
  - deploy

test:flutter:
  image: cirrusci/flutter
  stage: test
  script:
    - flutter test
  <<: *only-mr-branch-tag

build:android-apk-mr:
  image: cirrusci/flutter
  stage: build
  script:
    - flutter build apk --build-name=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME --build-number=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  artifacts:
    paths:
      - build/app/outputs/apk
    expire_in: 4h
  <<: *only-mr

build:android-apk-branch-tag:
  image: cirrusci/flutter
  stage: build
  script:
    - flutter build apk --build-name=$CI_COMMIT_REF_NAME --build-number=$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
    expire_in: 4h
  <<: *only-branch-tag

deploy:deploy-firebase:
  image: devillex/docker-firebase
  stage: deploy
  script:
    - firebase use --token $FIREBASE_TOKEN_CLI
    - firebase appdistribution:distribute build/app/outputs/apk/release/app-release.apk --app "$APP_ID_FIREBASE_ANDROID" --release-notes "$CI_COMMIT_REF_NAME" --groups "$GROUPE_TESTEUR" --token $FIREBASE_TOKEN_CLI
  <<: *only-mr-branch-tag
